name: GitHub Pages Astro CI

on:
  push:
    branches:
      - main  # Trigger deployment on main branch
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Fetch all history to allow full context

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'  # Use latest LTS version of Node.js

      # Install dependencies and browsers for testing
      - name: Install dependencies and Playwright browsers
        run: |
          npm install
          npx playwright install --with-deps

      # Run linters and tests before building
      - name: Run ESLint
        run: npx eslint .

      - name: Run Stylelint
        run: npx stylelint "src/**/*.astro"

      - name: Run HTMLHint
        run: npx htmlhint "**/*.html"

      - name: Run Astro Lint
        run: npx astro lint

      # Build the project
      - name: Build Astro project
        run: |
          npm run build  # Build the project using the build script in package.json
          npx astro build
          touch dist/.nojekyll  # Prevent Jekyll processing on GitHub Pages
          ls -la dist  # List contents of the build folder to check

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Directory to deploy
          publish_branch: gh-pages  # Deploy to the gh-pages branch

      # Run Playwright tests after deployment
      - name: Run Playwright tests
        run: npx playwright test
